FROM python:3.11-slim

# Imposta la directory di lavoro
WORKDIR /FibonacciGPT

# Copia i file della tua applicazione
COPY . .

# Installa le dipendenze
RUN pip install --no-cache-dir -r requirements.txt

# Espone la porta 5000
EXPOSE 5000

# Comando di avvio
CMD ["python", "main.py"]
